apiVersion: apps/v1
kind: Deployment
metadata:
 name: consumerapi
spec:
 selector:
   matchLabels:
     app: consumerapi
 template:
   metadata:
     labels:
       app: consumerapi
   spec:
     containers:
     - name: consumerapi
       image: sumyatphyoe/consumerapi
       ports:
       - containerPort: 8080
 
---
apiVersion: v1
kind: Service
metadata:
 name: consumerapi
spec:
 type: NodePort
 selector:
   app: consumerapi
 ports:
 - port: 81
   targetPort: 8080
   nodePort: 31500